// Skriv den rette datatype og et passende variabelnavn foran denne værdi; 
String teacherName = "Tess Løvgreen";
int daysInYear = 365;
String  city = "København";
boolean isTrue = true;
int minutesInDay = 60*24;
double decimal = 22.12;
String greetings = "Hej, jeg hedder "+teacherName;
boolean isFalse = false;
double sum = 2.2 + 33;
char initial = 'S';
